import { useTranslations, useLocale } from "next-intl";
import { getCvProficiencyLabels, getCvExtrasCategoryLabels, type CvLanguage } from "@/lib/cvLocale";

export function useEditorLabels() {
  const t = useTranslations();
  const locale = useLocale();
  const cvLang: CvLanguage = locale === "sv" ? "sv" : "en";
  const proficiency = getCvProficiencyLabels(cvLang);
  const extrasCats = getCvExtrasCategoryLabels(cvLang);

  const editor = {
    tabs: {
      template: t("editor.tabs.template"),
      basics: t("editor.tabs.basics"),
      summary: t("editor.tabs.summary"),
      experience: t("editor.tabs.experience"),
      education: t("editor.tabs.education"),
      skills: t("editor.tabs.skills"),
      languages: t("editor.tabs.languages"),
      extras: t("editor.tabs.extras"),
      visibility: t("editor.tabs.visibility"),
    },
    groups: {
      theme: t("editor.groups.theme"),
      content: t("editor.groups.content"),
      settings: t("editor.groups.settings"),
    },
    basics: {
      name: t("editor.basics.name"),
      nameRequired: t("editor.basics.nameRequired"),
      headline: t("editor.basics.headline"),
      email: t("editor.basics.email"),
      phone: t("editor.basics.phone"),
      location: t("editor.basics.location"),
      linkedIn: t("editor.basics.linkedIn"),
      website: t("editor.basics.website"),
      photo: t("editor.basics.photo"),
      photoUpload: t("editor.basics.photoUpload"),
      photoRemove: t("editor.basics.photoRemove"),
      photoTooLarge: t("editor.basics.photoTooLarge"),
    },
    summary: {
      label: t("editor.summary.label"),
      placeholder: t("editor.summary.placeholder"),
    },
    experience: {
      title: t("editor.experience.title"),
      company: t("editor.experience.company"),
      location: t("editor.experience.location"),
      startDate: t("editor.experience.startDate"),
      endDate: t("editor.experience.endDate"),
      datePlaceholder: t("editor.experience.datePlaceholder"),
      endDatePlaceholder: t("editor.experience.endDatePlaceholder"),
      description: t("editor.experience.description"),
      bullets: t("editor.experience.bullets"),
      bulletsHint: t("editor.experience.bulletsHint"),
      add: t("editor.experience.add"),
      remove: t("editor.experience.remove"),
      hide: t("editor.experience.hide"),
      show: t("editor.experience.show"),
      at: t("editor.experience.at"),
      emptyState: t("editor.experience.emptyState"),
      confirm: t("editor.experience.confirm"),
      moveUp: t("editor.experience.moveUp"),
      moveDown: t("editor.experience.moveDown"),
    },
    education: {
      institution: t("editor.education.institution"),
      degree: t("editor.education.degree"),
      field: t("editor.education.field"),
      startDate: t("editor.education.startDate"),
      endDate: t("editor.education.endDate"),
      datePlaceholder: t("editor.education.datePlaceholder"),
      endDatePlaceholder: t("editor.education.endDatePlaceholder"),
      description: t("editor.education.description"),
      add: t("editor.education.add"),
      remove: t("editor.education.remove"),
      hide: t("editor.education.hide"),
      show: t("editor.education.show"),
      emptyState: t("editor.education.emptyState"),
      confirm: t("editor.education.confirm"),
      moveUp: t("editor.education.moveUp"),
      moveDown: t("editor.education.moveDown"),
    },
    skills: {
      label: t("editor.skills.label"),
      placeholder: t("editor.skills.placeholder"),
      add: t("editor.skills.add"),
      emptyState: t("editor.skills.emptyState"),
      duplicateWarning: t("editor.skills.duplicateWarning"),
    },
    languages: {
      label: t("editor.languages.label"),
      placeholder: t("editor.languages.placeholder"),
      add: t("editor.languages.add"),
      levelLabel: t("editor.languages.levelLabel"),
      native: proficiency.native,
      full_professional: proficiency.full_professional,
      professional_working: proficiency.professional_working,
      limited_working: proficiency.limited_working,
      elementary: proficiency.elementary,
      noResults: t("editor.languages.noResults"),
      emptyState: t("editor.languages.emptyState"),
    },
    extras: {
      label: t("editor.extras.label"),
      placeholder: t("editor.extras.placeholder"),
      add: t("editor.extras.add"),
      addCategory: t("editor.extras.addCategory"),
      removeCategory: t("editor.extras.removeCategory"),
      emptyState: t("editor.extras.emptyState"),
    },
    extrasCategories: extrasCats,
    style: {
      styleTitle: t("editor.style.styleTitle"),
      styleDescription: t("editor.style.styleDescription"),
      accentColor: t("editor.style.accentColor"),
      secondaryColor: t("editor.style.secondaryColor"),
      photoSize: t("editor.style.photoSize"),
      fontScale: t("editor.style.fontScale"),
      photoShape: t("editor.style.photoShape"),
      photoShapeCircle: t("editor.style.photoShapeCircle"),
      photoShapeRounded: t("editor.style.photoShapeRounded"),
      photoShapeSquare: t("editor.style.photoShapeSquare"),
      sidebarBgColor: t("editor.style.sidebarBgColor"),
      lineHeight: t("editor.style.lineHeight"),
      resetDefaults: t("editor.style.resetDefaults"),
    },
    visibility: {
      title: t("editor.visibility.title"),
      description: t("editor.visibility.description"),
      photo: t("editor.visibility.photo"),
      summary: t("editor.visibility.summary"),
      experience: t("editor.visibility.experience"),
      education: t("editor.visibility.education"),
      skills: t("editor.visibility.skills"),
      languages: t("editor.visibility.languages"),
      extras: t("editor.visibility.extras"),
      contentLimitsTitle: t("editor.visibility.contentLimitsTitle"),
      contentLimitsDescription: t("editor.visibility.contentLimitsDescription"),
      maxExperience: t("editor.visibility.maxExperience"),
      maxEducation: t("editor.visibility.maxEducation"),
      maxSkills: t("editor.visibility.maxSkills"),
      maxBulletsPerJob: t("editor.visibility.maxBulletsPerJob"),
      summaryMaxChars: t("editor.visibility.summaryMaxChars"),
      maxExtras: t("editor.visibility.maxExtras"),
      simplifyLocationsTitle: t("editor.visibility.simplifyLocationsTitle"),
      simplifyLocationsDescription: t("editor.visibility.simplifyLocationsDescription"),
      simplifyLocations: t("editor.visibility.simplifyLocations"),
      cvLanguageTitle: t("editor.visibility.cvLanguageTitle"),
      cvLanguageDescription: t("editor.visibility.cvLanguageDescription"),
      cvLanguageEn: t("editor.visibility.cvLanguageEn"),
      cvLanguageSv: t("editor.visibility.cvLanguageSv"),
      template: t("editor.visibility.template"),
    },
  };

  const header = {
    importPdf: t("actions.importPdf"),
    downloadPdf: t("actions.downloadPdf"),
    generating: t("actions.generating"),
    moreActions: t("actions.moreActions"),
    themeToggle: t("theme.toggle"),
    help: t("help.trigger"),
  };

  const helpLabels = {
    title: t("help.title"),
    intro: t("help.intro"),
    howItWorksTitle: t("help.howItWorksTitle"),
    step1: t("help.step1"),
    step2: t("help.step2"),
    step3: t("help.step3"),
    downloadTitle: t("help.downloadTitle"),
    downloadText: t("help.downloadText"),
    dataTitle: t("help.dataTitle"),
    dataText: t("help.dataText"),
    footer: t("help.footer"),
  };

  const onboarding = {
    chooseTitle: t("onboarding.choose.title"),
    chooseSubtitle: t("onboarding.choose.subtitle"),
    importTitle: t("onboarding.choose.importTitle"),
    importDescription: t("onboarding.choose.importDescription"),
    scratchTitle: t("onboarding.choose.scratchTitle"),
    scratchDescription: t("onboarding.choose.scratchDescription"),
    howToGetPdf: t("onboarding.choose.howToGetPdf"),
    guideTitle: t("onboarding.guide.title"),
    guideStep1: t("onboarding.guide.step1"),
    guideStep2: t("onboarding.guide.step2"),
    guideStep3: t("onboarding.guide.step3"),
    uploadDropzone: t("upload.dropzone"),
    uploadProcessing: t("upload.processing"),
    uploadError: t("upload.error"),
    uploadTitle: t("upload.title"),
    successTitle: t("onboarding.success.title"),
    successScratchTitle: t("onboarding.success.scratchTitle"),
    successScratchDescription: t("onboarding.success.scratchDescription"),
    successCta: t("onboarding.success.cta"),
    successExperience: t("onboarding.success.experience"),
    successEducation: t("onboarding.success.education"),
    successSkills: t("onboarding.success.skills"),
    successBack: t("onboarding.success.back"),
  };

  const importDialog = {
    title: t("actions.importPdf"),
    warning: t("actions.importWarning"),
    dropzone: t("upload.dropzone"),
    processing: t("upload.processing"),
    error: t("upload.error"),
    cancel: t("actions.cancel"),
  };

  const footer = {
    copyright: t("footer.copyright", { year: new Date().getFullYear() }),
    openSource: t("footer.openSource"),
    cookieSettings: t("consent.settings"),
  };

  return { editor, header, helpLabels, onboarding, importDialog, footer };
}
